# Generated by Django 5.0.6 on 2024-05-13 11:29

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tournament_name', models.CharField(max_length=50)),
                ('tournament_rules', models.TextField()),
                ('participants', models.TextField()),
                ('squad', models.CharField(choices=[('Solo', 'Solo'), ('Duo', 'Duo'), ('Squad', 'Squad')], max_length=30)),
                ('weapon', models.CharField(choices=[('M416', 'M416'), ('M24', 'M24')], max_length=50)),
                ('started', models.BooleanField(blank=True, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('finished', models.BooleanField(blank=True, null=True)),
                ('available', models.BooleanField()),
            ],
        ),
    ]
