# Generated by Django 5.0.6 on 2024-05-13 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_tournament_tournament_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='Prize',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tournament',
            name='tournament_image',
            field=models.ImageField(blank=True, null=True, upload_to='tournament/'),
        ),
    ]
