# Generated by Django 5.0.6 on 2024-05-14 07:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_tournament_prize_alter_tournament_tournament_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyApply',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('FullName', models.CharField(max_length=80)),
                ('PubgName', models.CharField(max_length=50)),
                ('PubgID', models.CharField(max_length=20)),
                ('applydate', models.DateTimeField(auto_now_add=True)),
                ('tournament_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.tournament')),
            ],
        ),
    ]
