# Generated by Django 5.0.6 on 2024-05-14 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_tournament_isfull'),
    ]

    operations = [
        migrations.AddField(
            model_name='myapply',
            name='status',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
