# Generated by Django 5.0.6 on 2024-05-14 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_myapply_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myapply',
            name='status',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
