# Generated by Django 5.0.6 on 2024-05-14 11:18

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_round'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('player_1', models.CharField(max_length=50)),
                ('player_2', models.CharField(max_length=50)),
                ('overall_1', models.IntegerField(blank=True, default=0, null=True)),
                ('overall_2', models.IntegerField(blank=True, default=0, null=True)),
                ('matchvideo', models.CharField(blank=True, max_length=200, null=True)),
                ('forround', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.round')),
            ],
        ),
    ]
