# Generated by Django 5.0.6 on 2024-05-15 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_match'),
    ]

    operations = [
        migrations.AddField(
            model_name='myapply',
            name='tgusername',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
