# Generated by Django 5.0.6 on 2024-05-15 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_player'),
    ]

    operations = [
        migrations.AddField(
            model_name='round',
            name='tournament_winner',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
