# Generated by Django 5.0.6 on 2024-05-15 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_round_tournament_winner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='round',
            name='tournament_winner',
        ),
        migrations.AddField(
            model_name='match',
            name='tournament_winner',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
